# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/1440x1440/cover.qml) \
        $$quote($$BASEDIR/assets/720x1280/cover.qml) \
        $$quote($$BASEDIR/assets/720x720/cover.qml) \
        $$quote($$BASEDIR/assets/768x1280/cover.qml) \
        $$quote($$BASEDIR/assets/Hdmi.qml) \
        $$quote($$BASEDIR/assets/MainMenu.qml) \
        $$quote($$BASEDIR/assets/MupenMenuItem.qml) \
        $$quote($$BASEDIR/assets/about.qml) \
        $$quote($$BASEDIR/assets/backrest.qml) \
        $$quote($$BASEDIR/assets/glidecompat.qml) \
        $$quote($$BASEDIR/assets/helpers/AboutItem.qml) \
        $$quote($$BASEDIR/assets/helpers/ColourChooser.qml) \
        $$quote($$BASEDIR/assets/helpers/ControllerKeyBinding.qml) \
        $$quote($$BASEDIR/assets/helpers/KeyBinding.qml) \
        $$quote($$BASEDIR/assets/helpers/ShowHelpActionItem.qml) \
        $$quote($$BASEDIR/assets/history.qml) \
        $$quote($$BASEDIR/assets/html/Glide64compat.html) \
        $$quote($$BASEDIR/assets/images/Alternate.png) \
        $$quote($$BASEDIR/assets/images/Alternate1024Key.png) \
        $$quote($$BASEDIR/assets/images/Alternate1280Key.png) \
        $$quote($$BASEDIR/assets/images/Default.png) \
        $$quote($$BASEDIR/assets/images/Default1024Key.png) \
        $$quote($$BASEDIR/assets/images/Default1280Key.png) \
        $$quote($$BASEDIR/assets/images/DefaultStick.png) \
        $$quote($$BASEDIR/assets/images/Dual.png) \
        $$quote($$BASEDIR/assets/images/Dual1024Key.png) \
        $$quote($$BASEDIR/assets/images/Dual1280Key.png) \
        $$quote($$BASEDIR/assets/images/Fullscreen.png) \
        $$quote($$BASEDIR/assets/images/Fullscreen1024Key.png) \
        $$quote($$BASEDIR/assets/images/Fullscreen1280Key.png) \
        $$quote($$BASEDIR/assets/images/Keyboard.png) \
        $$quote($$BASEDIR/assets/images/Keyboard720Key.png) \
        $$quote($$BASEDIR/assets/images/KeyboardFlip.png) \
        $$quote($$BASEDIR/assets/images/KeyboardFlip720Key.png) \
        $$quote($$BASEDIR/assets/images/None.png) \
        $$quote($$BASEDIR/assets/images/back_black.png) \
        $$quote($$BASEDIR/assets/images/back_white.png) \
        $$quote($$BASEDIR/assets/images/backuprestore.png) \
        $$quote($$BASEDIR/assets/images/border.9.png) \
        $$quote($$BASEDIR/assets/images/borderfade.amd) \
        $$quote($$BASEDIR/assets/images/borderfade.png) \
        $$quote($$BASEDIR/assets/images/borderfadew.amd) \
        $$quote($$BASEDIR/assets/images/borderfadew.png) \
        $$quote($$BASEDIR/assets/images/borderpinned.png) \
        $$quote($$BASEDIR/assets/images/ca_bluetooth.png) \
        $$quote($$BASEDIR/assets/images/ca_stars_lg_active.png) \
        $$quote($$BASEDIR/assets/images/ca_stars_lg_half.png) \
        $$quote($$BASEDIR/assets/images/ca_stars_lg_inactive.png) \
        $$quote($$BASEDIR/assets/images/console.png) \
        $$quote($$BASEDIR/assets/images/controller.png) \
        $$quote($$BASEDIR/assets/images/coverq.png) \
        $$quote($$BASEDIR/assets/images/coverz.png) \
        $$quote($$BASEDIR/assets/images/default_icon.png) \
        $$quote($$BASEDIR/assets/images/esrb/Adults_Only.png) \
        $$quote($$BASEDIR/assets/images/esrb/Early_Childhood.png) \
        $$quote($$BASEDIR/assets/images/esrb/Everyone.png) \
        $$quote($$BASEDIR/assets/images/esrb/Everyone_10P.png) \
        $$quote($$BASEDIR/assets/images/esrb/Mature.png) \
        $$quote($$BASEDIR/assets/images/esrb/Rating_Pending.png) \
        $$quote($$BASEDIR/assets/images/esrb/Teen.png) \
        $$quote($$BASEDIR/assets/images/gameshark.png) \
        $$quote($$BASEDIR/assets/images/gametel.png) \
        $$quote($$BASEDIR/assets/images/hardware.png) \
        $$quote($$BASEDIR/assets/images/hardware_dk.png) \
        $$quote($$BASEDIR/assets/images/home.png) \
        $$quote($$BASEDIR/assets/images/ic_add_home.png) \
        $$quote($$BASEDIR/assets/images/ic_cancel.png) \
        $$quote($$BASEDIR/assets/images/ic_clear.png) \
        $$quote($$BASEDIR/assets/images/ic_hdmi.png) \
        $$quote($$BASEDIR/assets/images/ic_hdmi_dk.png) \
        $$quote($$BASEDIR/assets/images/ic_help.png) \
        $$quote($$BASEDIR/assets/images/ic_help3.png) \
        $$quote($$BASEDIR/assets/images/ic_history.png) \
        $$quote($$BASEDIR/assets/images/ic_info.png) \
        $$quote($$BASEDIR/assets/images/ic_lock.png) \
        $$quote($$BASEDIR/assets/images/ic_lock_dk.png) \
        $$quote($$BASEDIR/assets/images/ic_open.png) \
        $$quote($$BASEDIR/assets/images/ic_rename.png) \
        $$quote($$BASEDIR/assets/images/ic_settings.png) \
        $$quote($$BASEDIR/assets/images/ic_settings_dk.png) \
        $$quote($$BASEDIR/assets/images/ic_view_grid.png) \
        $$quote($$BASEDIR/assets/images/ic_view_list.png) \
        $$quote($$BASEDIR/assets/images/input/gp1.png) \
        $$quote($$BASEDIR/assets/images/input/gp1_dk.png) \
        $$quote($$BASEDIR/assets/images/input/gp2.png) \
        $$quote($$BASEDIR/assets/images/input/gp2_dk.png) \
        $$quote($$BASEDIR/assets/images/input/gp3.png) \
        $$quote($$BASEDIR/assets/images/input/gp3_dk.png) \
        $$quote($$BASEDIR/assets/images/input/gp4.png) \
        $$quote($$BASEDIR/assets/images/input/gp4_dk.png) \
        $$quote($$BASEDIR/assets/images/input/kbd1.png) \
        $$quote($$BASEDIR/assets/images/input/kbd1_dk.png) \
        $$quote($$BASEDIR/assets/images/input/kbd2.png) \
        $$quote($$BASEDIR/assets/images/input/kbd2_dk.png) \
        $$quote($$BASEDIR/assets/images/input/kbd3.png) \
        $$quote($$BASEDIR/assets/images/input/kbd3_dk.png) \
        $$quote($$BASEDIR/assets/images/input/kbd4.png) \
        $$quote($$BASEDIR/assets/images/input/kbd4_dk.png) \
        $$quote($$BASEDIR/assets/images/input/nn1.png) \
        $$quote($$BASEDIR/assets/images/input/nn1_dk.png) \
        $$quote($$BASEDIR/assets/images/input/nn2.png) \
        $$quote($$BASEDIR/assets/images/input/nn2_dk.png) \
        $$quote($$BASEDIR/assets/images/input/nn3.png) \
        $$quote($$BASEDIR/assets/images/input/nn3_dk.png) \
        $$quote($$BASEDIR/assets/images/input/nn4.png) \
        $$quote($$BASEDIR/assets/images/input/nn4_dk.png) \
        $$quote($$BASEDIR/assets/images/input/tk1.png) \
        $$quote($$BASEDIR/assets/images/input/tk1_dk.png) \
        $$quote($$BASEDIR/assets/images/input/tk2.png) \
        $$quote($$BASEDIR/assets/images/input/tk2_dk.png) \
        $$quote($$BASEDIR/assets/images/input/tk3.png) \
        $$quote($$BASEDIR/assets/images/input/tk3_dk.png) \
        $$quote($$BASEDIR/assets/images/input/tk4.png) \
        $$quote($$BASEDIR/assets/images/input/tk4_dk.png) \
        $$quote($$BASEDIR/assets/images/input/ts1.png) \
        $$quote($$BASEDIR/assets/images/input/ts1_dk.png) \
        $$quote($$BASEDIR/assets/images/input/ts2.png) \
        $$quote($$BASEDIR/assets/images/input/ts2_dk.png) \
        $$quote($$BASEDIR/assets/images/input/ts3.png) \
        $$quote($$BASEDIR/assets/images/input/ts3_dk.png) \
        $$quote($$BASEDIR/assets/images/input/ts4.png) \
        $$quote($$BASEDIR/assets/images/input/ts4_dk.png) \
        $$quote($$BASEDIR/assets/images/input.png) \
        $$quote($$BASEDIR/assets/images/input_dk.png) \
        $$quote($$BASEDIR/assets/images/logitech.png) \
        $$quote($$BASEDIR/assets/images/moga.png) \
        $$quote($$BASEDIR/assets/images/mupen64plus.png) \
        $$quote($$BASEDIR/assets/images/overlay/a.png) \
        $$quote($$BASEDIR/assets/images/overlay/analog.png) \
        $$quote($$BASEDIR/assets/images/overlay/b.png) \
        $$quote($$BASEDIR/assets/images/overlay/checkcircle.png) \
        $$quote($$BASEDIR/assets/images/overlay/cpad.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/a.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/b.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/cpad.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/dpad.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/l.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/r.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/start.png) \
        $$quote($$BASEDIR/assets/images/overlay/creator/z.png) \
        $$quote($$BASEDIR/assets/images/overlay/dpad.png) \
        $$quote($$BASEDIR/assets/images/overlay/emptycircle.png) \
        $$quote($$BASEDIR/assets/images/overlay/ic_create.png) \
        $$quote($$BASEDIR/assets/images/overlay/ic_create_big.png) \
        $$quote($$BASEDIR/assets/images/overlay/ic_hide_unhide.png) \
        $$quote($$BASEDIR/assets/images/overlay/l.png) \
        $$quote($$BASEDIR/assets/images/overlay/lgood.png) \
        $$quote($$BASEDIR/assets/images/overlay/overflow.png) \
        $$quote($$BASEDIR/assets/images/overlay/r.png) \
        $$quote($$BASEDIR/assets/images/overlay/rgood.png) \
        $$quote($$BASEDIR/assets/images/overlay/start.png) \
        $$quote($$BASEDIR/assets/images/overlay/z.png) \
        $$quote($$BASEDIR/assets/images/overlay.png) \
        $$quote($$BASEDIR/assets/images/pin.png) \
        $$quote($$BASEDIR/assets/images/pinned.png) \
        $$quote($$BASEDIR/assets/images/pinned2.png) \
        $$quote($$BASEDIR/assets/images/players/four.png) \
        $$quote($$BASEDIR/assets/images/players/four_d.png) \
        $$quote($$BASEDIR/assets/images/players/single.png) \
        $$quote($$BASEDIR/assets/images/players/single_d.png) \
        $$quote($$BASEDIR/assets/images/players/three.png) \
        $$quote($$BASEDIR/assets/images/players/three_d.png) \
        $$quote($$BASEDIR/assets/images/players/two.png) \
        $$quote($$BASEDIR/assets/images/players/two_d.png) \
        $$quote($$BASEDIR/assets/images/razer.png) \
        $$quote($$BASEDIR/assets/images/save_load.png) \
        $$quote($$BASEDIR/assets/images/save_load0.png) \
        $$quote($$BASEDIR/assets/images/save_load1.png) \
        $$quote($$BASEDIR/assets/images/save_load2.png) \
        $$quote($$BASEDIR/assets/images/save_load3.png) \
        $$quote($$BASEDIR/assets/images/save_load4.png) \
        $$quote($$BASEDIR/assets/images/save_load5.png) \
        $$quote($$BASEDIR/assets/images/save_load6.png) \
        $$quote($$BASEDIR/assets/images/save_load7.png) \
        $$quote($$BASEDIR/assets/images/save_load8.png) \
        $$quote($$BASEDIR/assets/images/save_load9.png) \
        $$quote($$BASEDIR/assets/images/sound.png) \
        $$quote($$BASEDIR/assets/images/sound_dk.png) \
        $$quote($$BASEDIR/assets/images/steelseries.png) \
        $$quote($$BASEDIR/assets/images/titlebar.png) \
        $$quote($$BASEDIR/assets/images/titlebar_dark.png) \
        $$quote($$BASEDIR/assets/images/unpin.png) \
        $$quote($$BASEDIR/assets/images/video.png) \
        $$quote($$BASEDIR/assets/images/video_dk.png) \
        $$quote($$BASEDIR/assets/images/wii.png) \
        $$quote($$BASEDIR/assets/images/xbox360.png) \
        $$quote($$BASEDIR/assets/images/xbox360w.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/overlayCreator.qml) \
        $$quote($$BASEDIR/assets/play.qml) \
        $$quote($$BASEDIR/assets/rominfo.qml) \
        $$quote($$BASEDIR/assets/settings/AudioSettings.qml) \
        $$quote($$BASEDIR/assets/settings/ControllerSettings.qml) \
        $$quote($$BASEDIR/assets/settings/GamepadSettings.qml) \
        $$quote($$BASEDIR/assets/settings/GeneralSettings.qml) \
        $$quote($$BASEDIR/assets/settings/GlideSettings.qml) \
        $$quote($$BASEDIR/assets/settings/HardwareSettings.qml) \
        $$quote($$BASEDIR/assets/settings/InputSettings.qml) \
        $$quote($$BASEDIR/assets/settings/KeyboardSettings.qml) \
        $$quote($$BASEDIR/assets/settings/N64Settings.qml) \
        $$quote($$BASEDIR/assets/settings/RiceINISettings.qml) \
        $$quote($$BASEDIR/assets/settings/RiceOptions.qml) \
        $$quote($$BASEDIR/assets/settings/RiceSettings.qml) \
        $$quote($$BASEDIR/assets/settings/SettingsToggle.qml) \
        $$quote($$BASEDIR/assets/settings/ThemeSettings.qml) \
        $$quote($$BASEDIR/assets/settings/TouchKeyboardSettings.qml) \
        $$quote($$BASEDIR/assets/settings/TouchscreenSettings.qml) \
        $$quote($$BASEDIR/assets/settings/VideoSettings.qml) \
        $$quote($$BASEDIR/assets/shortcut.qml) \
        $$quote($$BASEDIR/assets/temp/160-1.jpg) \
        $$quote($$BASEDIR/assets/temp/160-2.jpg) \
        $$quote($$BASEDIR/assets/temp/160-3.jpg) \
        $$quote($$BASEDIR/assets/temp/160-g.jpg) \
        $$quote($$BASEDIR/assets/temp/160.png) \
        $$quote($$BASEDIR/assets/temp/screens.xml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/BPS/BpsEventHandler.cpp) \
        $$quote($$BASEDIR/src/Cover/sceneCover.cpp) \
        $$quote($$BASEDIR/src/GameInfo/GameImage.cpp) \
        $$quote($$BASEDIR/src/GameInfo/GameInfo.cpp) \
        $$quote($$BASEDIR/src/History/Game.cpp) \
        $$quote($$BASEDIR/src/NetRequest.cpp) \
        $$quote($$BASEDIR/src/OverlayCreator.cpp) \
        $$quote($$BASEDIR/src/RiceINI.cpp) \
        $$quote($$BASEDIR/src/cheat.cpp) \
        $$quote($$BASEDIR/src/compare_core.cpp) \
        $$quote($$BASEDIR/src/core_interface.cpp) \
        $$quote($$BASEDIR/src/emulator.cpp) \
        $$quote($$BASEDIR/src/frontend.cpp) \
        $$quote($$BASEDIR/src/imageloader.cpp) \
        $$quote($$BASEDIR/src/imageprocessor.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/osal_dynamiclib_unix.cpp) \
        $$quote($$BASEDIR/src/osal_files_unix.cpp) \
        $$quote($$BASEDIR/src/plugin.cpp) \
        $$quote($$BASEDIR/src/settings/M64PSettings.cpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/AudioSettings.cpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/GeneralSettings.cpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/HardwareSettings.cpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/InputSettings.cpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/VideoSettings.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/BPS/BpsEventHandler.hpp) \
        $$quote($$BASEDIR/src/Cover/sceneCover.hpp) \
        $$quote($$BASEDIR/src/GameInfo/GameImage.hpp) \
        $$quote($$BASEDIR/src/GameInfo/GameInfo.hpp) \
        $$quote($$BASEDIR/src/History/Game.hpp) \
        $$quote($$BASEDIR/src/NetRequest.hpp) \
        $$quote($$BASEDIR/src/RiceINI.hpp) \
        $$quote($$BASEDIR/src/cheat.h) \
        $$quote($$BASEDIR/src/compare_core.h) \
        $$quote($$BASEDIR/src/core_interface.h) \
        $$quote($$BASEDIR/src/emulator.h) \
        $$quote($$BASEDIR/src/frontend.h) \
        $$quote($$BASEDIR/src/imageloader.hpp) \
        $$quote($$BASEDIR/src/imageprocessor.hpp) \
        $$quote($$BASEDIR/src/main.h) \
        $$quote($$BASEDIR/src/osal_dynamiclib.h) \
        $$quote($$BASEDIR/src/osal_files.h) \
        $$quote($$BASEDIR/src/osal_preproc.h) \
        $$quote($$BASEDIR/src/plugin.h) \
        $$quote($$BASEDIR/src/settings/M64PSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/AudioSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/GamepadInputSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/GeneralSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/GlideVideoSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/HardwareSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/InputSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/KeyboardInputSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/N64VideoSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/RiceVideoSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/SettingsBase.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/TouchKeyboardInputSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/TouchscreenInputSettings.hpp) \
        $$quote($$BASEDIR/src/settings/SettingsInternal/VideoSettings.hpp) \
        $$quote($$BASEDIR/src/version.h)
}

INCLUDEPATH += $$quote($$BASEDIR/src/settings) \
    $$quote($$BASEDIR/src/History) \
    $$quote($$BASEDIR/src/BPS) \
    $$quote($$BASEDIR/src/settings/SettingsInternal) \
    $$quote($$BASEDIR/src) \
    $$quote($$BASEDIR/src/GameInfo) \
    $$quote($$BASEDIR/src/Cover)

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/BPS/*.c) \
        $$quote($$BASEDIR/../src/BPS/*.c++) \
        $$quote($$BASEDIR/../src/BPS/*.cc) \
        $$quote($$BASEDIR/../src/BPS/*.cpp) \
        $$quote($$BASEDIR/../src/BPS/*.cxx) \
        $$quote($$BASEDIR/../src/Cover/*.c) \
        $$quote($$BASEDIR/../src/Cover/*.c++) \
        $$quote($$BASEDIR/../src/Cover/*.cc) \
        $$quote($$BASEDIR/../src/Cover/*.cpp) \
        $$quote($$BASEDIR/../src/Cover/*.cxx) \
        $$quote($$BASEDIR/../src/GameInfo/*.c) \
        $$quote($$BASEDIR/../src/GameInfo/*.c++) \
        $$quote($$BASEDIR/../src/GameInfo/*.cc) \
        $$quote($$BASEDIR/../src/GameInfo/*.cpp) \
        $$quote($$BASEDIR/../src/GameInfo/*.cxx) \
        $$quote($$BASEDIR/../src/History/*.c) \
        $$quote($$BASEDIR/../src/History/*.c++) \
        $$quote($$BASEDIR/../src/History/*.cc) \
        $$quote($$BASEDIR/../src/History/*.cpp) \
        $$quote($$BASEDIR/../src/History/*.cxx) \
        $$quote($$BASEDIR/../src/settings/*.c) \
        $$quote($$BASEDIR/../src/settings/*.c++) \
        $$quote($$BASEDIR/../src/settings/*.cc) \
        $$quote($$BASEDIR/../src/settings/*.cpp) \
        $$quote($$BASEDIR/../src/settings/*.cxx) \
        $$quote($$BASEDIR/../src/settings/SettingsInternal/*.c) \
        $$quote($$BASEDIR/../src/settings/SettingsInternal/*.c++) \
        $$quote($$BASEDIR/../src/settings/SettingsInternal/*.cc) \
        $$quote($$BASEDIR/../src/settings/SettingsInternal/*.cpp) \
        $$quote($$BASEDIR/../src/settings/SettingsInternal/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qml) \
        $$quote($$BASEDIR/../assets/1440x1440/*.js) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/*.js) \
        $$quote($$BASEDIR/../assets/720x720/*.qs) \
        $$quote($$BASEDIR/../assets/768x1280/*.qml) \
        $$quote($$BASEDIR/../assets/768x1280/*.js) \
        $$quote($$BASEDIR/../assets/768x1280/*.qs) \
        $$quote($$BASEDIR/../assets/helpers/*.qml) \
        $$quote($$BASEDIR/../assets/helpers/*.js) \
        $$quote($$BASEDIR/../assets/helpers/*.qs) \
        $$quote($$BASEDIR/../assets/html/*.qml) \
        $$quote($$BASEDIR/../assets/html/*.js) \
        $$quote($$BASEDIR/../assets/html/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/esrb/*.qml) \
        $$quote($$BASEDIR/../assets/images/esrb/*.js) \
        $$quote($$BASEDIR/../assets/images/esrb/*.qs) \
        $$quote($$BASEDIR/../assets/images/input/*.qml) \
        $$quote($$BASEDIR/../assets/images/input/*.js) \
        $$quote($$BASEDIR/../assets/images/input/*.qs) \
        $$quote($$BASEDIR/../assets/images/overlay/*.qml) \
        $$quote($$BASEDIR/../assets/images/overlay/*.js) \
        $$quote($$BASEDIR/../assets/images/overlay/*.qs) \
        $$quote($$BASEDIR/../assets/images/overlay/creator/*.qml) \
        $$quote($$BASEDIR/../assets/images/overlay/creator/*.js) \
        $$quote($$BASEDIR/../assets/images/overlay/creator/*.qs) \
        $$quote($$BASEDIR/../assets/images/players/*.qml) \
        $$quote($$BASEDIR/../assets/images/players/*.js) \
        $$quote($$BASEDIR/../assets/images/players/*.qs) \
        $$quote($$BASEDIR/../assets/settings/*.qml) \
        $$quote($$BASEDIR/../assets/settings/*.js) \
        $$quote($$BASEDIR/../assets/settings/*.qs) \
        $$quote($$BASEDIR/../assets/temp/*.qml) \
        $$quote($$BASEDIR/../assets/temp/*.js) \
        $$quote($$BASEDIR/../assets/temp/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
